import {decodeEventLog,type Abi} from 'viem';
import {db} from '../db/index.js';
import {abi,manifest,publicClient,stringify,read} from '../chain/client.js';
export function projection(event:string,a:any,e:{tx:string,log_index:number,chain_id:number,block:string,ts:string,trader:string}):{sql:string,values:unknown[]}|null{
 const b=a.batchId;
 if(event==='Converted')return {sql:'INSERT INTO conversions VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) ON CONFLICT DO NOTHING',values:[e.tx,e.log_index,e.chain_id,e.block,e.ts,a.fromToken,a.toToken,a.sharesMoved,a.feeBps,a.filledByHook,e.trader]};
 if(event==='Committed')return{sql:'INSERT INTO orders(batch_id,trader,commit_hash) VALUES($1,$2,$3) ON CONFLICT(batch_id,trader) DO UPDATE SET commit_hash=EXCLUDED.commit_hash',values:[b,a.trader.toLowerCase(),a.hash]};
 if(event==='Revealed')return{sql:'INSERT INTO orders(batch_id,trader,revealed,is_buy,qty,limit_px,route_residual) VALUES($1,$2,true,$3,$4,$5,$6) ON CONFLICT(batch_id,trader) DO UPDATE SET revealed=true,is_buy=EXCLUDED.is_buy,qty=EXCLUDED.qty,limit_px=EXCLUDED.limit_px,route_residual=EXCLUDED.route_residual',values:[b,a.trader.toLowerCase(),a.isBuy,a.qty,a.limitPx,a.routeResidual]};
 if(event==='MidSelected')return{sql:'INSERT INTO batches(batch_id,mid,mid_source) VALUES($1,$2,$3) ON CONFLICT(batch_id) DO UPDATE SET mid=EXCLUDED.mid,mid_source=EXCLUDED.mid_source',values:[b,a.price,Number(a.source)===0?'Chainlink':'TWAP']};
 if(event==='BatchSettled')return{sql:"INSERT INTO batches(batch_id,phase,mid,crossed_qty,routed_qty,settled_tx) VALUES($1,'Settled',$2,$3,$4,$5) ON CONFLICT(batch_id) DO UPDATE SET phase='Settled',mid=EXCLUDED.mid,crossed_qty=EXCLUDED.crossed_qty,routed_qty=EXCLUDED.routed_qty,settled_tx=EXCLUDED.settled_tx",values:[b,a.mid,a.crossedQty,a.routedQty,e.tx]};
 if(event==='Crossed'||event==='RoutedToLit')return{sql:'INSERT INTO fills VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT DO NOTHING',values:[b,a.trader.toLowerCase(),a.isBuy,a.qty,a.mid??a.avgPx,event==='Crossed'?'cross':'lit',e.tx,e.log_index]};return null;
}
let busy=false;
export async function catchup(rescan=false){if(busy)return;busy=true;try{const m=manifest();const latest=await publicClient.getBlockNumber();const curs=await db.query('SELECT last_block FROM cursor WHERE chain_id=$1',[m.chainId]);const previous=BigInt(curs.rows[0]?.last_block??m.blockNumber);let start=rescan?(previous>10n?previous-10n:BigInt(m.blockNumber)):previous+1n;if(!curs.rowCount)start=BigInt(m.blockNumber);if(start<BigInt(m.blockNumber))start=BigInt(m.blockNumber);
const combined=[...abi('ParityHook'),...abi('DarkCrossHook'),...abi('CanonicalStock')] as Abi;
for(let from=start;from<=latest;from+=2000n){const to=from+1999n>latest?latest:from+1999n;const logs=await publicClient.getLogs({address:[m.contracts.parityHook,m.contracts.darkCrossHook,m.contracts.vault],fromBlock:from,toBlock:to});const events=[];for(const log of logs){try{const decoded=decodeEventLog({abi:combined,data:log.data,topics:log.topics});const [block,tx]=await Promise.all([publicClient.getBlock({blockNumber:log.blockNumber}),publicClient.getTransaction({hash:log.transactionHash})]);events.push({chain_id:m.chainId,block:log.blockNumber.toString(),block_hash:log.blockHash,tx:log.transactionHash,log_index:log.logIndex,event_name:decoded.eventName,args:JSON.parse(stringify(decoded.args)),ts:block.timestamp.toString(),trader:tx.from.toLowerCase()})}catch(error){if(String(error).includes('Decode'))continue;throw error}}
const c=await db.connect();try{await c.query('BEGIN');await c.query('DELETE FROM chain_events WHERE chain_id=$1 AND block BETWEEN $2 AND $3',[m.chainId,from.toString(),to.toString()]);for(const e of events)await c.query('INSERT INTO chain_events VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING',[e.chain_id,e.block,e.block_hash,e.tx,e.log_index,e.event_name,e.args,e.ts,e.trader]);
// Rebuild projections from the canonical journal so orphaned reveals and settlements disappear.
await c.query('TRUNCATE conversions,batches,orders,fills');const all=await c.query('SELECT * FROM chain_events ORDER BY block,log_index');for(const e of all.rows){const p=projection(e.event_name,e.args,e);if(p)await c.query(p.sql,p.values)}await c.query('INSERT INTO cursor VALUES($1,$2) ON CONFLICT(chain_id) DO UPDATE SET last_block=EXCLUDED.last_block',[m.chainId,to.toString()]);await c.query('COMMIT')}catch(err){await c.query('ROLLBACK');throw err}finally{c.release()}}
const [backing]=await Promise.all([read('vault','backing')]);for(const i of backing[0])await db.query('INSERT INTO backing_snapshots VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING',[latest.toString(),i.token,i.tokensHeld.toString(),i.spt.toString(),i.sharesRepresented.toString(),backing[2].toString()]);for(const p of m.pools.filter(p=>p.kind==='parity'))for(const currency of [p.key.currency0,p.key.currency1]){const [amount,fee]=await Promise.all([read('parityHook','inventory',[currency]),read('parityHook','feeAccrued',[currency])]);await db.query('INSERT INTO hook_inventory VALUES($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING',[latest.toString(),p.id,currency,amount.toString(),fee.toString()])}
}finally{busy=false}}
export async function startIndexer(){await catchup(true);const m=manifest();const stop=publicClient.watchContractEvent({address:[m.contracts.parityHook,m.contracts.darkCrossHook],abi:[...abi('ParityHook'),...abi('DarkCrossHook')],onLogs:()=>void catchup(true).catch(console.error),onError:console.error});const timer=setInterval(()=>void catchup(true).catch(console.error),4000);return()=>{stop();clearInterval(timer)}}
