/** The Unison MCP server (packages/mcp on the mcp branch): what an agent connects to and what it can call. */
export const MCP_URL = "https://nichars-mac-mini.tail43cacc.ts.net/mcp";
export const CLAUDE_CODE_CMD = `claude mcp add unison --transport http ${MCP_URL}`;

export const MCP_TOOLS: { name: string; args: string; kind: "read" | "executes"; body: string }[] = [
  { name: "list_assets", args: "", kind: "read", body: "Assets, their issuer wrappers and live multipliers (shares per token)." },
  { name: "get_pool", args: "asset", kind: "read", body: "Inventory per wrapper, skew, fee each direction (base + skew) and the cheap direction now." },
  { name: "quote_convert", args: "asset, fromWrapper, toWrapper, amount", kind: "read", body: "On-chain quote: shares out, base and skew fee, what you keep." },
  { name: "convert", args: "asset, fromWrapper, toWrapper, amount, recipient?", kind: "executes", body: "Converts through the demo relay; returns the tx hash, Uniscan link and fee split." },
  { name: "get_batch", args: "asset", kind: "read", body: "Dark Cross batch phase and time left, plus the last settled batch." },
  { name: "commit_dark_order", args: "asset, side, amount", kind: "executes", body: "Commits a sealed Dark Cross order through the relay; returns the commit tx and batch id." },
];

/** The recorded agent run, generated by scripts/gen-mcp-demo.py from submission/mcp-demo.md (receipt checked on-chain). */
export type McpDemo = {
  client: string;
  prompt: string;
  steps: { tool: string; args: Record<string, unknown>; result: string }[];
  tx: string;
  block: number;
  explorer: string;
  source: string;
};
// Globbed like the deployment manifest, so the page still builds before the transcript file exists.
const files = import.meta.glob<McpDemo>("../../../deployments/unichain-sepolia.mcp-demo.json", { eager: true, import: "default" });
export const mcpDemo: McpDemo | undefined = Object.values(files)[0];

/** `quote_convert(asset: "AAPL", amount: 50)` */
export const callText = (s: McpDemo["steps"][number]) =>
  `${s.tool}(${Object.entries(s.args)
    .map(([k, v]) => `${k}: ${JSON.stringify(v)}`)
    .join(", ")})`;
