/** The recorded agent run, generated by scripts/gen-mcp-demo.py from submission/mcp-demo.md (receipt checked on-chain). */
export type McpDemo = {
  client: string;
  prompt: string;
  steps: { tool: string; args: Record<string, unknown>; result: string }[];
  tx: string;
  block: number;
  explorer: string;
  source: string;
};
// Globbed like the deployment manifest, so the page still builds before the transcript file exists.
const files = import.meta.glob<McpDemo>("../../../deployments/unichain-sepolia.mcp-demo.json", { eager: true, import: "default" });
export const mcpDemo: McpDemo | undefined = Object.values(files)[0];
