// Regenerates packages/types/src/generated/* and the §2 events table of INTERFACES.md.
// Inputs: compiled interface artifacts (contracts/out, from `forge build`) and fenced `wrapswap:*` blocks in INTERFACES.md.
// Deterministic: running twice on the same inputs produces byte-identical output.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { toEventSelector, type AbiEvent, type AbiParameter } from "viem";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const outDir = resolve(here, "../src/generated");
const interfacesPath = resolve(root, "INTERFACES.md");
const HEADER = "// GENERATED by packages/types/scripts/generate.ts (make types). Do not edit.\n";

// Interface artifacts: [artifact file, contract name].
const INTERFACES: [string, string][] = [
  ["IParityHook.sol", "IParityHook"],
  ["IDarkCrossHook.sol", "IDarkCrossHook"],
  ["IEligibility.sol", "IEligibility"],
  ["IEligibility.sol", "IEASEligibility"],
  ["IPriceOracle.sol", "IPriceOracle"],
  ["IPriceOracle.sol", "IMockPriceOracle"],
  ["IWrapperAdapter.sol", "IWrapperAdapter"],
  ["IMockIssuerToken.sol", "IMockIssuerToken"],
  ["IIssuerRegistry.sol", "IIssuerRegistry"],
  ["IWrapSwapRouter.sol", "IWrapSwapRouter"],
];
// Events inherited from IERC20 are standard and not part of the indexer contract.
const EXCLUDED_EVENTS = new Set(["Transfer", "Approval"]);

type Json = null | boolean | number | string | Json[] | { [k: string]: Json };
type SchemaDef = { [k: string]: Json };

function fail(msg: string): never {
  console.error(`generate: ${msg}`);
  process.exit(1);
}

// ---------- INTERFACES.md blocks ----------
const doc = readFileSync(interfacesPath, "utf8");
const blocks = [...doc.matchAll(/```json wrapswap:(\w+)(?: (\w+))?\n([\s\S]*?)```/g)].map((m) => {
  try {
    return { kind: m[1], name: m[2], body: JSON.parse(m[3]) as Json };
  } catch (e) {
    fail(`invalid JSON in wrapswap:${m[1]} ${m[2] ?? ""}: ${(e as Error).message}`);
  }
});
const schemas: Record<string, SchemaDef> = {};
for (const b of blocks.filter((b) => b.kind === "schema")) {
  if (!b.name) fail("wrapswap:schema block without a name");
  if (schemas[b.name]) fail(`duplicate schema ${b.name}`);
  schemas[b.name] = b.body as SchemaDef;
}
const routes = blocks.find((b) => b.kind === "routes")?.body as { [k: string]: Json }[] | undefined;
const demo = blocks.find((b) => b.kind === "demo")?.body;
if (!routes || !demo) fail("missing wrapswap:routes or wrapswap:demo block");

function refs(s: Json, acc = new Set<string>()): Set<string> {
  if (Array.isArray(s)) s.forEach((x) => refs(x, acc));
  else if (s && typeof s === "object")
    for (const [k, v] of Object.entries(s)) {
      if (k === "$ref" && typeof v === "string") acc.add(v);
      else refs(v, acc);
    }
  return acc;
}
for (const [name, s] of Object.entries(schemas))
  for (const r of refs(s)) if (!schemas[r]) fail(`schema ${name} references unknown ${r}`);
for (const r of routes) {
  for (const key of ["query", "response"] as const) {
    const v = r[key];
    if (v !== null && (typeof v !== "string" || !schemas[v])) fail(`route ${r.path} ${key} ${v} is not a schema`);
  }
  if (typeof r.backing !== "string" || r.backing.length === 0) fail(`route ${r.path} has no backing`);
}

// ---------- TS types from schemas ----------
const HEX_REFS = new Set(["Address", "Bytes32"]);
function tsType(s: SchemaDef, indent = ""): string {
  if (typeof s.$ref === "string") return s.$ref;
  if (Array.isArray(s.anyOf)) return s.anyOf.map((x) => tsType(x as SchemaDef, indent)).join(" | ");
  if ("const" in s) return JSON.stringify(s.const);
  if (Array.isArray(s.enum)) return s.enum.map((x) => JSON.stringify(x)).join(" | ");
  const types = s.type === undefined ? [] : Array.isArray(s.type) ? (s.type as string[]) : [s.type as string];
  if (types.length === 0) return "unknown";
  return types
    .map((t) => {
      switch (t) {
        case "string":
          return typeof s.pattern === "string" && s.pattern.startsWith("^0x") ? "`0x${string}`" : "string";
        case "integer":
        case "number":
          return "number";
        case "boolean":
          return "boolean";
        case "null":
          return "null";
        case "array":
          return `Array<${s.items ? tsType(s.items as SchemaDef, indent) : "unknown"}>`;
        case "object": {
          const props = (s.properties ?? {}) as Record<string, SchemaDef>;
          const required = new Set((s.required ?? []) as string[]);
          const inner = indent + "  ";
          const lines = Object.entries(props).map(
            ([k, v]) => `${inner}${JSON.stringify(k)}${required.has(k) ? "" : "?"}: ${tsType(v, inner)};`,
          );
          if (s.additionalProperties && typeof s.additionalProperties === "object")
            lines.push(`${inner}[key: string]: ${tsType(s.additionalProperties as SchemaDef, inner)};`);
          return lines.length ? `{\n${lines.join("\n")}\n${indent}}` : "Record<string, never>";
        }
        default:
          return fail(`unsupported type ${t}`);
      }
    })
    .join(" | ");
}

const schemaNames = Object.keys(schemas).sort();
let schemasTs = HEADER + 'import type { Schema } from "../validate.js";\n\n';
schemasTs += `export const schemas = ${JSON.stringify(Object.fromEntries(schemaNames.map((n) => [n, schemas[n]])), null, 2)} as const satisfies Record<string, Schema>;\n\n`;
schemasTs += "export type SchemaName = keyof typeof schemas;\n\n";
for (const n of schemaNames)
  schemasTs += `export type ${n} = ${HEX_REFS.has(n) ? "`0x${string}`" : tsType(schemas[n])};\n\n`;
schemasTs += `/** INTERFACES.md §5 route table. */\nexport const routes = ${JSON.stringify(routes, null, 2)} as const;\n\n`;
schemasTs += "export type RouteName = (typeof routes)[number][\"name\"];\n";
schemasTs += `export type RouteResponses = {\n${routes.map((r) => `  ${JSON.stringify(r.name)}: ${r.response};`).join("\n")}\n};\n`;
schemasTs += `export type RouteQueries = {\n${routes.map((r) => `  ${JSON.stringify(r.name)}: ${r.query ?? "Record<string, never>"};`).join("\n")}\n};\n`;

let validatorsTs = HEADER;
validatorsTs += 'import { check, ValidationError, type Schema } from "../validate.js";\n';
validatorsTs += `import { schemas, type SchemaName, ${schemaNames.join(", ")} } from "./schemas.js";\n\n`;
validatorsTs += "const defs = schemas as unknown as Record<string, Schema>;\n\n";
validatorsTs += "/** Violations of the named INTERFACES.md schema; empty when valid. */\n";
validatorsTs += "export const validate = (name: SchemaName, value: unknown): string[] => check(defs, { $ref: name }, value);\n\n";
for (const n of schemaNames) {
  validatorsTs += `export const is${n} = (value: unknown): value is ${n} => validate(${JSON.stringify(n)}, value).length === 0;\n`;
  validatorsTs += `export function assert${n}(value: unknown): ${n} {\n  const errors = validate(${JSON.stringify(n)}, value);\n  if (errors.length) throw new ValidationError(${JSON.stringify(n)}, errors);\n  return value as ${n};\n}\n`;
}
validatorsTs += `\nexport const validators = {\n${schemaNames.map((n) => `  ${n}: { is: is${n}, assert: assert${n} },`).join("\n")}\n} as const;\n`;

// ---------- ABIs and events ----------
type AbiItem = { type: string; name?: string; inputs?: AbiParameter[] };
const abis: Record<string, AbiItem[]> = {};
for (const [file, name] of INTERFACES) {
  const path = resolve(root, "contracts/out", file, `${name}.json`);
  let artifact: { abi: AbiItem[] };
  try {
    artifact = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    fail(`missing ${path}; run forge build first`);
  }
  abis[name] = artifact.abi;
}

let abisTs = HEADER;
for (const [name, abi] of Object.entries(abis)) abisTs += `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n\n`;
abisTs += `export const abis = {\n${Object.keys(abis).map((n) => `  ${n}: ${n}Abi,`).join("\n")}\n} as const;\n`;

function tsEventType(p: AbiParameter): string {
  const t = p.type;
  if (t === "bool") return "boolean";
  if (t === "string") return "string";
  if (t === "address" || t.startsWith("bytes")) return "`0x${string}`";
  const m = /^(u?int)(\d*)$/.exec(t);
  if (m) return Number(m[2] || 256) <= 48 ? "number" : "bigint"; // viem decoding convention
  return fail(`unsupported event param type ${t}`);
}

type EventRow = { contract: string; event: AbiEvent; signature: string; topic0: string };
const events: EventRow[] = [];
const seen = new Set<string>();
for (const [contract, abi] of Object.entries(abis))
  for (const item of abi.filter((i) => i.type === "event") as unknown as AbiEvent[]) {
    if (EXCLUDED_EVENTS.has(item.name)) continue;
    const signature = `${item.name}(${item.inputs.map((i) => i.type).join(",")})`;
    if (seen.has(signature)) continue;
    seen.add(signature);
    events.push({ contract, event: item, signature, topic0: toEventSelector(item) });
  }

let eventsTs = HEADER;
eventsTs += `/** topic0 by "Contract.Event". */\nexport const topics = {\n${events.map((e) => `  ${JSON.stringify(`${e.contract}.${e.event.name}`)}: ${JSON.stringify(e.topic0)},`).join("\n")}\n} as const;\n\n`;
eventsTs += "export type EventKey = keyof typeof topics;\n\n";
eventsTs += `/** Canonical signatures by "Contract.Event". */\nexport const eventSignatures = {\n${events.map((e) => `  ${JSON.stringify(`${e.contract}.${e.event.name}`)}: ${JSON.stringify(e.signature)},`).join("\n")}\n} as const satisfies Record<EventKey, string>;\n\n`;
eventsTs += `/** Decoded event args (viem decoding: ints of <= 48 bits are number). */\nexport type EventArgs = {\n${events
  .map(
    (e) =>
      `  ${JSON.stringify(`${e.contract}.${e.event.name}`)}: {\n${e.event.inputs.map((i) => `    ${i.name}: ${tsEventType(i)};`).join("\n")}\n  };`,
  )
  .join("\n")}\n};\n`;

// ---------- demo constants ----------
function tsLiteral(v: Json, indent = ""): string {
  if (typeof v === "string" && /^-?\d+$/.test(v)) return `${v}n`;
  if (Array.isArray(v)) return `[${v.map((x) => tsLiteral(x, indent)).join(", ")}]`;
  if (v && typeof v === "object") {
    const inner = indent + "  ";
    return `{\n${Object.entries(v)
      .map(([k, x]) => `${inner}${/^[A-Za-z_$][\w$]*$/.test(k) ? k : JSON.stringify(k)}: ${tsLiteral(x, inner)},`)
      .join("\n")}\n${indent}}`;
  }
  return JSON.stringify(v);
}
const demoTs = `${HEADER}/** INTERFACES.md §10 canonical demo narrative (digit strings are bigint). */\nexport const DEMO = ${tsLiteral(demo)} as const;\n\nexport type Demo = typeof DEMO;\n`;

// ---------- write ----------
mkdirSync(outDir, { recursive: true });
const files: Record<string, string> = {
  "abis.ts": abisTs,
  "events.ts": eventsTs,
  "schemas.ts": schemasTs,
  "validators.ts": validatorsTs,
  "demo.ts": demoTs,
};
for (const [f, content] of Object.entries(files)) writeFileSync(resolve(outDir, f), content);

// ---------- INTERFACES.md §2 table ----------
const indexedSig = (e: AbiEvent) =>
  `${e.name}(${e.inputs.map((i) => `${(i as { internalType?: string }).internalType?.replace(/^(contract|enum|struct) /, "").replace(/^I\w+\./, "") ?? i.type}${i.indexed ? " indexed" : ""} ${i.name}`).join(", ")})`;
const table = [
  "| Contract | Event (indexed params marked) | topic0 |",
  "|---|---|---|",
  ...events.map((e) => `| ${e.contract} | \`${indexedSig(e.event)}\` | \`${e.topic0}\` |`),
].join("\n");
const begin = "<!-- BEGIN GENERATED: events -->";
const end = "<!-- END GENERATED: events -->";
const start = doc.indexOf(begin);
const stop = doc.indexOf(end);
if (start < 0 || stop < start) fail("INTERFACES.md is missing the generated events markers");
const nextDoc = `${doc.slice(0, start + begin.length)}\n${table}\n${doc.slice(stop)}`;
if (nextDoc !== doc) writeFileSync(interfacesPath, nextDoc);

// ---------- §1 reproduces every interface file verbatim ----------
for (const file of new Set(INTERFACES.map(([f]) => f))) {
  const source = readFileSync(resolve(root, "contracts/src/interfaces", file), "utf8").trim();
  if (!doc.includes(source)) fail(`INTERFACES.md §1 does not reproduce contracts/src/interfaces/${file} verbatim`);
}

// ---------- coverage: every §2 event consumed by a §6 table ----------
const s6 = doc.slice(doc.indexOf("## 6."), doc.indexOf("## 7."));
const uncovered = events.filter((e) => !s6.includes(`\`${e.event.name}\``));
if (uncovered.length) fail(`events without a §6 table: ${uncovered.map((e) => e.event.name).join(", ")}`);

console.log(
  `generate: ${Object.keys(abis).length} ABIs, ${events.length} events, ${schemaNames.length} schemas, ${routes.length} routes`,
);
